"""Static core fallback-template definitions."""
from __future__ import annotations

from typing import Any


def core_fallback_templates(source_refs: dict[str, str]) -> list[dict[str, Any]]:
    """Return the core ranked fallback catalog entries."""

    return [
        {
            "rank": 1,
            "pipeline_id": "sr_rna_splicing_rmats_star",
            "use_case": "Short-read RNA-seq alternative splicing (control vs treatment) with STAR + rMATS.",
            "assumptions": ["paired-end short-read FASTQ", "two sample groups", "reference FASTA + GTF available"],
            "required_inputs": ["two_group_fastq_pairs", "reference_fasta", "annotation_gtf"],
            "optional_inputs": ["subset_mode", "test_reads_per_fastq", "star_index_cache_root", "control_tag", "treatment_tag"],
            "expected_outputs": ["outputs/splicing_auto/rmats/SE.MATS.JCEC.txt", "group BAM list files", "FastQC outputs"],
            "required_tools": ["star", "rmats", "samtools", "fastqc"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "splicing_analysis", "reference_inputs", "group_comparison", "differential_analysis"],
            "keywords": ["splicing", "rmats", "alternative splicing"],
            "cache_hints": ["outputs/_cache/star_indexes/*/genomeParameters.txt", "outputs/splicing_auto/rmats/SE.MATS.JCEC.txt"],
            "primary_sources": [source_refs["star"], source_refs["rmats"]],
        },
        {
            "rank": 2,
            "pipeline_id": "differential_expression_deseq2",
            "use_case": "Short-read RNA-seq differential expression with STAR/featureCounts and DESeq2.",
            "assumptions": ["paired-end short-read FASTQ", "two sample groups", "reference FASTA + GTF available"],
            "required_inputs": ["two_group_fastq_pairs", "reference_fasta", "annotation_gtf"],
            "optional_inputs": ["subset_mode", "test_reads_per_fastq", "star_index_cache_root", "control_tag", "treatment_tag"],
            "expected_outputs": ["featureCounts count matrix", "DESeq2 results table", "group BAM list files"],
            "required_tools": ["star", "samtools", "featureCounts", "Rscript"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "quantification", "differential_analysis", "group_comparison", "reference_inputs"],
            "keywords": ["deseq2", "differential expression", "rna-seq"],
            "cache_hints": ["outputs/_cache/star_indexes/*/genomeParameters.txt", "outputs/fallback/differential_expression_deseq2/featurecounts_gene_counts.txt"],
            "primary_sources": [source_refs["deseq2"], source_refs["star"]],
        },
        {
            "rank": 3,
            "pipeline_id": "differential_expression_edger",
            "use_case": "Short-read RNA-seq differential expression with edgeR-style interface.",
            "assumptions": ["paired-end short-read FASTQ", "two sample groups", "reference FASTA + GTF available"],
            "required_inputs": ["two_group_fastq_pairs", "reference_fasta", "annotation_gtf"],
            "optional_inputs": ["subset_mode", "test_reads_per_fastq", "control_tag", "treatment_tag"],
            "expected_outputs": ["featureCounts count matrix", "differential results TSV"],
            "required_tools": ["star", "samtools", "featureCounts", "Rscript"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "quantification", "differential_analysis", "group_comparison", "reference_inputs"],
            "keywords": ["edger", "differential expression"],
            "cache_hints": ["outputs/_cache/star_indexes/*/genomeParameters.txt"],
            "primary_sources": [source_refs["edger"], source_refs["star"]],
        },
        {
            "rank": 4,
            "pipeline_id": "differential_expression_limma_voom",
            "use_case": "Short-read RNA-seq differential expression with limma-voom-style interface.",
            "assumptions": ["paired-end short-read FASTQ", "two sample groups", "reference FASTA + GTF available"],
            "required_inputs": ["two_group_fastq_pairs", "reference_fasta", "annotation_gtf"],
            "optional_inputs": ["subset_mode", "test_reads_per_fastq", "control_tag", "treatment_tag"],
            "expected_outputs": ["featureCounts count matrix", "differential results TSV"],
            "required_tools": ["star", "samtools", "featureCounts", "Rscript"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "quantification", "differential_analysis", "group_comparison", "reference_inputs"],
            "keywords": ["limma", "voom", "differential expression"],
            "cache_hints": ["outputs/_cache/star_indexes/*/genomeParameters.txt"],
            "primary_sources": [source_refs["limma"], source_refs["star"]],
        },
        {
            "rank": 5,
            "pipeline_id": "sr_rna_align_star_2pass",
            "use_case": "Short-read RNA-seq splice-aware alignment with STAR 2-pass mode.",
            "assumptions": ["paired-end short-read FASTQ", "reference FASTA + GTF available"],
            "required_inputs": ["fastq_pairs", "reference_fasta", "annotation_gtf"],
            "optional_inputs": ["star_index_cache_root"],
            "expected_outputs": ["coordinate-sorted BAM", "STAR logs"],
            "required_tools": ["star", "samtools"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "reference_inputs"],
            "keywords": ["star", "rna alignment", "2-pass"],
            "cache_hints": ["outputs/_cache/star_indexes/*/genomeParameters.txt", "outputs/fallback/sr_rna_align_star_2pass/star_Aligned.out.bam"],
            "primary_sources": [source_refs["star"]],
        },
        {
            "rank": 6,
            "pipeline_id": "sr_rna_align_hisat2",
            "use_case": "Short-read RNA-seq alignment with HISAT2.",
            "assumptions": ["paired-end short-read FASTQ", "reference FASTA available"],
            "required_inputs": ["fastq_pairs", "reference_fasta"],
            "optional_inputs": ["annotation_gtf", "aligner_index_cache_root"],
            "expected_outputs": ["sorted BAM", "BAM index"],
            "required_tools": ["hisat2", "samtools"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "optional"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "reference_inputs"],
            "keywords": ["hisat2", "alignment"],
            "cache_hints": ["outputs/_cache/aligner_indexes/hisat2_genome.1.ht2"],
            "primary_sources": [source_refs["hisat2"]],
        },
        {
            "rank": 7,
            "pipeline_id": "sr_dna_align_bwa_mem",
            "use_case": "Short-read DNA alignment using BWA-MEM.",
            "assumptions": ["paired-end short-read FASTQ", "reference FASTA available"],
            "required_inputs": ["fastq_pairs", "reference_fasta"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["sorted BAM", "BAM index"],
            "required_tools": ["bwa", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "reference_inputs"],
            "keywords": ["bwa", "dna alignment"],
            "cache_hints": ["outputs/_cache/aligner_indexes/bwa_genome.bwt"],
            "primary_sources": [source_refs["bwa"]],
        },
        {
            "rank": 8,
            "pipeline_id": "sr_dna_align_bowtie2",
            "use_case": "Short-read DNA alignment using Bowtie2.",
            "assumptions": ["paired-end short-read FASTQ", "reference FASTA available"],
            "required_inputs": ["fastq_pairs", "reference_fasta"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["sorted BAM", "BAM index"],
            "required_tools": ["bowtie2", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "reference_inputs"],
            "keywords": ["bowtie2", "dna alignment"],
            "cache_hints": ["outputs/_cache/aligner_indexes/bowtie2_genome.1.bt2"],
            "primary_sources": [source_refs["bowtie2"]],
        },
        {
            "rank": 9,
            "pipeline_id": "lr_rna_align_minimap2_splice",
            "use_case": "Long-read RNA alignment using minimap2 spliced preset.",
            "assumptions": ["long-read FASTQ", "reference FASTA available"],
            "required_inputs": ["long_reads_fastq", "reference_fasta"],
            "optional_inputs": ["annotation_gtf", "aligner_index_cache_root"],
            "expected_outputs": ["sorted BAM", "BAM index"],
            "required_tools": ["minimap2", "samtools"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "optional"},
            "supports_short_read": False,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "reference_inputs"],
            "keywords": ["long read", "minimap2", "splice"],
            "cache_hints": ["outputs/_cache/aligner_indexes/lr_rna_align_minimap2_splice.mmi"],
            "primary_sources": [source_refs["minimap2"]],
        },
        {
            "rank": 10,
            "pipeline_id": "lr_dna_align_minimap2",
            "use_case": "Long-read DNA alignment using minimap2 ONT/PacBio presets.",
            "assumptions": ["long-read FASTQ", "reference FASTA available"],
            "required_inputs": ["long_reads_fastq", "reference_fasta"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["sorted BAM", "BAM index"],
            "required_tools": ["minimap2", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": False,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "reference_inputs"],
            "keywords": ["long read", "minimap2", "dna"],
            "cache_hints": ["outputs/_cache/aligner_indexes/lr_dna_align_minimap2.mmi"],
            "primary_sources": [source_refs["minimap2"]],
        },
        {
            "rank": 11,
            "pipeline_id": "germline_variant_gatk_haplotypecaller",
            "use_case": "Germline variant calling with GATK HaplotypeCaller.",
            "assumptions": ["reference FASTA available", "aligned BAM available or can be produced"],
            "required_inputs": ["reference_fasta", "fastq_pairs_or_bam"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["germline VCF.gz"],
            "required_tools": ["gatk", "bwa", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "variant_calling", "reference_inputs"],
            "keywords": ["germline", "haplotypecaller", "gatk"],
            "cache_hints": ["outputs/fallback/germline_variant_gatk_haplotypecaller/germline.vcf.gz"],
            "primary_sources": [source_refs["gatk_hc"]],
        },
        {
            "rank": 12,
            "pipeline_id": "germline_variant_bcftools",
            "use_case": "Germline variant calling with bcftools mpileup/call.",
            "assumptions": ["reference FASTA available", "aligned BAM available or can be produced"],
            "required_inputs": ["reference_fasta", "fastq_pairs_or_bam"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["germline VCF.gz"],
            "required_tools": ["bcftools", "bwa", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "variant_calling", "reference_inputs"],
            "keywords": ["germline", "bcftools", "variant"],
            "cache_hints": ["outputs/fallback/germline_variant_bcftools/germline.vcf.gz"],
            "primary_sources": [source_refs["bcftools"]],
        },
        {
            "rank": 13,
            "pipeline_id": "germline_variant_varscan",
            "use_case": "Germline variant calling with VarScan2 mpileup2cns.",
            "assumptions": ["reference FASTA available", "aligned BAM available or can be produced"],
            "required_inputs": ["reference_fasta", "fastq_pairs_or_bam"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["germline VCF"],
            "required_tools": ["varscan", "bwa", "samtools", "java"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "medium",
            "contract_capabilities": ["alignment", "variant_calling", "reference_inputs"],
            "keywords": ["germline", "varscan", "varscan2", "variant"],
            "cache_hints": ["outputs/fallback/germline_variant_varscan/germline.vcf"],
            "primary_sources": [source_refs["varscan"]],
        },
        {
            "rank": 14,
            "pipeline_id": "germline_variant_freebayes",
            "use_case": "Germline variant calling with FreeBayes.",
            "assumptions": ["reference FASTA available", "aligned BAM available or can be produced"],
            "required_inputs": ["reference_fasta", "fastq_pairs_or_bam"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["germline VCF"],
            "required_tools": ["freebayes", "bwa", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["alignment", "variant_calling", "reference_inputs"],
            "keywords": ["germline", "freebayes", "variant"],
            "cache_hints": ["outputs/fallback/germline_variant_freebayes/germline.vcf"],
            "primary_sources": [source_refs["freebayes"]],
        },
        {
            "rank": 15,
            "pipeline_id": "somatic_variant_mutect2_tn",
            "use_case": "Somatic variant calling with Mutect2 in tumor-normal mode.",
            "assumptions": ["two groups (control and treatment)", "reference FASTA available", "paired-end FASTQ or BAM inputs"],
            "required_inputs": ["reference_fasta", "two_group_fastq_pairs_or_bam"],
            "optional_inputs": ["pon_vcf", "germline_resource_vcf"],
            "expected_outputs": ["somatic VCF.gz"],
            "required_tools": ["gatk", "bwa", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "medium",
            "contract_capabilities": ["alignment", "variant_calling", "group_comparison", "reference_inputs"],
            "keywords": ["somatic", "mutect2", "tumor", "normal"],
            "cache_hints": ["outputs/fallback/somatic_variant_mutect2_tn/somatic.vcf.gz"],
            "primary_sources": [source_refs["gatk_mutect2"]],
        },
        {
            "rank": 16,
            "pipeline_id": "somatic_variant_bcftools_tn_degrade",
            "use_case": "Somatic-like tumor-normal calling using bcftools with tumor-minus-normal subtraction (degrade path).",
            "assumptions": ["two groups (control and treatment)", "reference FASTA available", "paired-end FASTQ or BAM inputs"],
            "required_inputs": ["reference_fasta", "two_group_fastq_pairs_or_bam"],
            "optional_inputs": ["aligner_index_cache_root"],
            "expected_outputs": ["somatic-like VCF.gz"],
            "required_tools": ["bcftools", "bwa", "samtools"],
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "medium",
            "contract_capabilities": ["alignment", "variant_calling", "group_comparison", "reference_inputs"],
            "keywords": ["somatic", "tumor", "normal", "bcftools"],
            "cache_hints": ["outputs/fallback/somatic_variant_bcftools_tn_degrade/somatic_like.vcf.gz"],
            "primary_sources": [source_refs["bcftools"]],
        },
        {
            "rank": 17,
            "pipeline_id": "differential_expression_deseq2_from_counts",
            "use_case": "Differential expression from existing count matrix + metadata with DESeq2.",
            "assumptions": ["count matrix and metadata already available"],
            "required_inputs": ["counts_matrix", "metadata_table"],
            "optional_inputs": ["design_formula", "contrast"],
            "expected_outputs": ["DESeq2 results TSV"],
            "required_tools": ["Rscript"],
            "reference_requirements": {},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["differential_analysis", "group_comparison"],
            "keywords": ["deseq2", "count matrix", "differential expression"],
            "cache_hints": ["outputs/fallback/differential_expression_deseq2_from_counts/deseq2_out/deseq2_results.tsv"],
            "primary_sources": [source_refs["deseq2"]],
        },
        {
            "rank": 17,
            "pipeline_id": "alt_splicing_dexseq",
            "use_case": "Alternative splicing / exon usage analysis with DEXSeq-style interface.",
            "assumptions": ["paired-end short-read FASTQ", "two sample groups", "reference FASTA + GTF available"],
            "required_inputs": ["two_group_fastq_pairs", "reference_fasta", "annotation_gtf"],
            "optional_inputs": ["subset_mode", "test_reads_per_fastq", "control_tag", "treatment_tag"],
            "expected_outputs": ["exon-level count matrix", "DEXSeq-style output tables"],
            "required_tools": ["star", "samtools", "featureCounts", "Rscript"],
            "reference_requirements": {"reference_fasta": "required", "annotation_gtf": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "medium",
            "contract_capabilities": ["alignment", "splicing_analysis", "differential_analysis", "group_comparison", "reference_inputs"],
            "keywords": ["dexseq", "exon usage", "splicing"],
            "cache_hints": ["outputs/fallback/alt_splicing_dexseq/dexseq_out/deseq2_results.tsv"],
            "primary_sources": [source_refs["dexseq"], source_refs["star"]],
        },
        {
            "rank": 18,
            "pipeline_id": "alt_splicing_majiq",
            "use_case": "Alternative splicing quantification with MAJIQ.",
            "assumptions": ["group-labeled BAMs or FASTQs available"],
            "required_inputs": ["two_group_fastq_pairs_or_bam"],
            "optional_inputs": ["annotation_gtf", "reference_fasta"],
            "expected_outputs": ["MAJIQ deltapsi outputs"],
            "required_tools": ["majiq"],
            "reference_requirements": {"annotation_gtf": "optional"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "medium",
            "contract_capabilities": ["splicing_analysis", "group_comparison"],
            "keywords": ["majiq", "splicing", "deltapsi"],
            "cache_hints": ["outputs/fallback/alt_splicing_majiq"],
            "primary_sources": [source_refs["majiq_paper"]],
        },
    ]
