"""Static specialty fallback-template definitions."""
from __future__ import annotations

from typing import Any


def specialty_fallback_templates(source_refs: dict[str, str]) -> list[dict[str, Any]]:
    """Return the specialty tail of the ranked fallback catalog."""

    return [
        {
            "rank": 19,
            "pipeline_id": "protein_blastp_homology",
            "use_case": "Protein homology search using BLASTP.",
            "assumptions": ["protein FASTA query available", "BLAST database available"],
            "required_inputs": ["protein_fasta"],
            "optional_inputs": ["protein_database", "evalue", "threads"],
            "expected_outputs": ["BLAST tabular hits"],
            "required_tools": ["blastp"],
            "reference_requirements": {"protein_database": "optional"},
            "supports_short_read": False,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["protein_analysis", "annotation"],
            "keywords": ["protein", "blastp", "homology"],
            "cache_hints": ["outputs/fallback/protein_blastp_homology/blastp.tsv"],
            "primary_sources": [source_refs["blast"]],
        },
        {
            "rank": 20,
            "pipeline_id": "protein_hmmscan_domains",
            "use_case": "Protein domain analysis using HMMER hmmscan.",
            "assumptions": ["protein FASTA query available", "HMM database available"],
            "required_inputs": ["protein_fasta"],
            "optional_inputs": ["hmm_db", "threads"],
            "expected_outputs": ["domain hit table", "hmmscan report"],
            "required_tools": ["hmmscan"],
            "reference_requirements": {"hmm_db": "optional"},
            "supports_short_read": False,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["protein_analysis", "annotation"],
            "keywords": ["protein", "hmmscan", "pfam", "domain"],
            "cache_hints": ["outputs/fallback/protein_hmmscan_domains/hmmscan.tbl"],
            "primary_sources": [source_refs["hmmer"]],
        },
        {
            "rank": 21,
            "pipeline_id": "protein_prokka_annotation",
            "use_case": "Protein/gene functional annotation using Prokka.",
            "assumptions": ["nucleotide/protein FASTA input available"],
            "required_inputs": ["protein_fasta"],
            "optional_inputs": ["sample_prefix"],
            "expected_outputs": ["annotated GFF/FAA files"],
            "required_tools": ["prokka"],
            "reference_requirements": {},
            "supports_short_read": False,
            "supports_long_read": False,
            "recovery_safety": "medium",
            "contract_capabilities": ["annotation", "protein_analysis"],
            "keywords": ["protein annotation", "prokka", "annotation"],
            "cache_hints": ["outputs/fallback/protein_prokka_annotation/prokka"],
            "primary_sources": [source_refs["prokka"]],
        },
        {
            "rank": 21,
            "pipeline_id": "variant_annotation_vep",
            "use_case": "Variant effect annotation using Ensembl VEP.",
            "assumptions": ["input VCF available"],
            "required_inputs": ["vcf"],
            "optional_inputs": ["assembly", "cache_dir"],
            "expected_outputs": ["annotated VCF"],
            "required_tools": ["vep"],
            "reference_requirements": {},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["annotation", "variant_calling"],
            "keywords": ["vep", "variant annotation"],
            "cache_hints": ["outputs/fallback/variant_annotation_vep/annotated.vcf"],
            "primary_sources": [source_refs["vep"]],
        },
        {
            "rank": 22,
            "pipeline_id": "variant_annotation_snpeff",
            "use_case": "Variant effect annotation using snpEff.",
            "assumptions": ["input VCF available"],
            "required_inputs": ["vcf"],
            "optional_inputs": ["genome_db"],
            "expected_outputs": ["annotated VCF"],
            "required_tools": ["snpEff"],
            "reference_requirements": {},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["annotation", "variant_calling"],
            "keywords": ["snpeff", "variant annotation"],
            "cache_hints": ["outputs/fallback/variant_annotation_snpeff/annotated.vcf"],
            "primary_sources": [source_refs["snpeff"]],
        },
        {
            "rank": 23,
            "pipeline_id": "methylation_bismark_style",
            "use_case": "Uncommon bisulfite methylation analysis using Bismark-style wrapper.",
            "assumptions": ["paired-end FASTQ", "Bismark genome folder available or references staged"],
            "required_inputs": ["fastq_pairs", "reference_fasta"],
            "optional_inputs": ["threads", "sample_name"],
            "expected_outputs": ["methylation summary TSV"],
            "required_tools": ["bismark"],
            "tool_wrappers": ["methylation_bismark_style"],
            "skill_name": "methylation_bismark_style",
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["methylation_analysis", "alignment", "reference_inputs"],
            "contract_coverage_signals": {
                "methylation_analysis": ["methylation", "bisulfite", "bismark"],
                "alignment": ["reads_1", "reads_2"],
                "reference_inputs": ["genome_folder", "reference_fasta"],
            },
            "keywords": ["methylation", "bisulfite", "bismark"],
            "cache_hints": ["outputs/fallback/methylation_bismark_style/methylation_summary.tsv"],
            "primary_sources": [source_refs["bismark"]],
        },
        {
            "rank": 24,
            "pipeline_id": "metagenomics_kraken2_bracken_style",
            "use_case": "Uncommon metagenomics profiling with Kraken2/Bracken-style wrapper.",
            "assumptions": ["paired-end FASTQ", "Kraken2 database available"],
            "required_inputs": ["fastq_pairs"],
            "optional_inputs": ["database", "threads", "read_len"],
            "expected_outputs": ["Bracken abundance TSV"],
            "required_tools": ["kraken2", "bracken"],
            "tool_wrappers": ["metagenomics_kraken2_bracken_style"],
            "skill_name": "metagenomics_kraken2_bracken_style",
            "reference_requirements": {},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["metagenomics_profiling"],
            "contract_coverage_signals": {
                "metagenomics_profiling": ["metagenomics", "kraken2", "bracken"],
            },
            "keywords": ["metagenomics", "kraken2", "bracken", "taxonomy"],
            "cache_hints": ["outputs/fallback/metagenomics_kraken2_bracken_style/bracken_abundance.tsv"],
            "primary_sources": [source_refs["kraken2"], source_refs["bracken"]],
        },
        {
            "rank": 25,
            "pipeline_id": "fusion_star_fusion_style",
            "use_case": "Uncommon RNA fusion detection using STAR-Fusion-style wrapper.",
            "assumptions": ["paired-end FASTQ", "CTAT genome library available"],
            "required_inputs": ["fastq_pairs"],
            "optional_inputs": ["genome_lib_dir", "threads"],
            "expected_outputs": ["fusion prediction TSV"],
            "required_tools": ["star-fusion"],
            "tool_wrappers": ["fusion_star_fusion_style"],
            "skill_name": "fusion_star_fusion_style",
            "reference_requirements": {},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "medium",
            "contract_capabilities": ["fusion_detection", "alignment"],
            "contract_coverage_signals": {
                "fusion_detection": ["fusion", "star-fusion"],
                "alignment": ["reads_1", "reads_2"],
            },
            "keywords": ["fusion", "star-fusion", "transcript fusion"],
            "cache_hints": ["outputs/fallback/fusion_star_fusion_style/fusions.tsv"],
            "primary_sources": [source_refs["star_fusion"]],
        },
        {
            "rank": 26,
            "pipeline_id": "cnv_cnvkit_style",
            "use_case": "Uncommon CNV analysis using CNVkit-style wrapper.",
            "assumptions": ["aligned BAM available or can be built from FASTQ", "reference FASTA available"],
            "required_inputs": ["fastq_pairs_or_bam", "reference_fasta"],
            "optional_inputs": ["threads"],
            "expected_outputs": ["CNV summary TSV"],
            "required_tools": ["cnvkit.py", "bwa", "samtools"],
            "tool_wrappers": ["cnv_cnvkit_style", "bwa_mem_align"],
            "skill_name": "cnv_cnvkit_style",
            "reference_requirements": {"reference_fasta": "required"},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "medium",
            "contract_capabilities": ["cnv_analysis", "reference_inputs", "alignment"],
            "contract_coverage_signals": {
                "cnv_analysis": ["cnv", "copy number", "cnvkit"],
                "reference_inputs": ["reference_fasta"],
                "alignment": ["input_bam", "bwa_mem_align"],
            },
            "keywords": ["cnv", "copy number", "cnvkit"],
            "cache_hints": ["outputs/fallback/cnv_cnvkit_style/cnv_summary.tsv"],
            "primary_sources": [source_refs["cnvkit"], source_refs["bwa"]],
        },
        {
            "rank": 27,
            "pipeline_id": "immune_repertoire_mixcr_style",
            "use_case": "Uncommon immune repertoire profiling with MiXCR-style wrapper.",
            "assumptions": ["paired-end FASTQ"],
            "required_inputs": ["fastq_pairs"],
            "optional_inputs": ["threads"],
            "expected_outputs": ["clone summary TSV"],
            "required_tools": ["mixcr"],
            "tool_wrappers": ["immune_repertoire_mixcr_style"],
            "skill_name": "immune_repertoire_mixcr_style",
            "reference_requirements": {},
            "supports_short_read": True,
            "supports_long_read": False,
            "recovery_safety": "high",
            "contract_capabilities": ["immune_repertoire_profiling"],
            "contract_coverage_signals": {
                "immune_repertoire_profiling": ["immune repertoire", "mixcr", "tcr", "bcr"],
            },
            "keywords": ["immune repertoire", "mixcr", "tcr", "bcr", "clonotype"],
            "cache_hints": ["outputs/fallback/immune_repertoire_mixcr_style/clones.tsv"],
            "primary_sources": [source_refs["mixcr"]],
        },
        {
            "rank": 28,
            "pipeline_id": "phylogenetics_iqtree_style",
            "use_case": "Uncommon phylogenetics workflow with IQ-TREE-style wrapper.",
            "assumptions": ["sequence alignment FASTA available or can be synthesized"],
            "required_inputs": ["protein_fasta"],
            "optional_inputs": ["model", "threads", "seed"],
            "expected_outputs": ["Newick tree file"],
            "required_tools": ["iqtree2"],
            "tool_wrappers": ["phylogenetics_iqtree_style"],
            "skill_name": "phylogenetics_iqtree_style",
            "reference_requirements": {},
            "supports_short_read": True,
            "supports_long_read": True,
            "recovery_safety": "high",
            "contract_capabilities": ["phylogenetics", "protein_analysis"],
            "contract_coverage_signals": {
                "phylogenetics": ["phylogeny", "iqtree", "tree"],
                "protein_analysis": ["fasta", "alignment"],
            },
            "keywords": ["phylogeny", "phylogenetics", "iqtree", "tree"],
            "cache_hints": ["outputs/fallback/phylogenetics_iqtree_style/tree.nwk"],
            "primary_sources": [source_refs["iqtree"]],
        },
    ]
