"""Stable facade for workflow-template I/O and reference resolution helpers."""

from __future__ import annotations

from bio_harness.workflows.template_alignment_support import (
    alignment_bam_hints_for_step,
    candidate_star_bam_variants,
    repair_alignment_dependent_bam_input,
    repair_featurecounts_input_bams,
)
from bio_harness.workflows.template_fastq_support import (
    discover_fastq_pair_map,
    extract_read_hint,
    extract_sample_hint,
    get_fastq_pair_map,
    repair_fastqc_input_files,
    resolve_fastq_pair_from_hints,
    resolve_single_fastq_from_hints,
)
from bio_harness.workflows.template_io_base import (
    DEFAULT_STAR_INDEX_CACHE_ROOT,
    PROJECT_ROOT,
    PIPELINE_SCRIPT_DIR,
    STRUCTURED_READ_PAIR_TOOLS,
    STRUCTURED_STAR_GENOME_DIR_TOOLS,
    annotation_reference_kind,
    bash_output_hints_for_command,
    dedupe_preserve_order,
    extend_output_hints,
    is_structured_output_key,
    new_canonicalization_state,
    normalize_structured_argument_aliases,
    normalize_structured_output_path,
    parse_path_tokens,
    path_matches_planned_outputs,
    path_within_root,
    register_output_path_rewrite,
    render_path_tokens,
    rewrite_output_dependency_path,
    script_command,
    structured_output_hints_for_step,
)
from bio_harness.workflows.template_reference_support import (
    BASH_REFERENCE_FLAG_KINDS,
    discover_star_index_dirs,
    infer_workspace_root,
    pick_reference_file,
    pick_star_index_dir,
    rewrite_bash_reference_flags,
)

__all__ = [
    "BASH_REFERENCE_FLAG_KINDS",
    "DEFAULT_STAR_INDEX_CACHE_ROOT",
    "PIPELINE_SCRIPT_DIR",
    "PROJECT_ROOT",
    "STRUCTURED_READ_PAIR_TOOLS",
    "STRUCTURED_STAR_GENOME_DIR_TOOLS",
    "alignment_bam_hints_for_step",
    "annotation_reference_kind",
    "bash_output_hints_for_command",
    "candidate_star_bam_variants",
    "dedupe_preserve_order",
    "discover_fastq_pair_map",
    "discover_star_index_dirs",
    "extend_output_hints",
    "extract_read_hint",
    "extract_sample_hint",
    "get_fastq_pair_map",
    "infer_workspace_root",
    "is_structured_output_key",
    "new_canonicalization_state",
    "normalize_structured_argument_aliases",
    "normalize_structured_output_path",
    "parse_path_tokens",
    "path_matches_planned_outputs",
    "path_within_root",
    "pick_reference_file",
    "pick_star_index_dir",
    "register_output_path_rewrite",
    "render_path_tokens",
    "repair_alignment_dependent_bam_input",
    "repair_fastqc_input_files",
    "repair_featurecounts_input_bams",
    "resolve_fastq_pair_from_hints",
    "resolve_single_fastq_from_hints",
    "rewrite_bash_reference_flags",
    "rewrite_output_dependency_path",
    "script_command",
    "structured_output_hints_for_step",
]
