"""Generate standard ``SKILL.md`` packages from Bio-Harness tool contracts.

Bio-Harness historically stores executable bioinformatics capabilities as
Markdown files with YAML frontmatter under ``bio_harness/skills/definitions``.
Those files are machine-readable tool contracts, not standard agent skill
packages. This script creates a standard package facade for each contract:

``bio_harness/skills/catalog/<name>/SKILL.md``
``bio_harness/skills/catalog/<name>/contract.yaml``

The generated files do not change runtime behavior. They make the capability
surface easier to review and package while preserving the strict typed contract
used by the harness.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DEFINITIONS_DIR = PROJECT_ROOT / "bio_harness" / "skills" / "definitions"
DEFAULT_CATALOG_DIR = PROJECT_ROOT / "bio_harness" / "skills" / "catalog"
GENERATED_HEADER = (
    "<!-- Generated by scripts/generate_standard_skill_packages.py. "
    "Edit the source tool contract, then regenerate. -->"
)
REQUIRED_CONTRACT_FIELDS = ("name", "description", "risk_level", "parameters")


class SkillPackageError(ValueError):
    """Raised when a source tool contract cannot be converted safely."""


def _split_frontmatter(raw_text: str, source_path: Path) -> tuple[dict[str, Any], str]:
    """Return YAML frontmatter metadata and Markdown body from a source file.

    Args:
        raw_text: Raw Markdown text from a tool contract file.
        source_path: Path used only for actionable error messages.

    Returns:
        A tuple containing parsed metadata and the remaining Markdown body.

    Raises:
        SkillPackageError: If the source file does not contain valid mapping
            frontmatter.
    """
    lines = raw_text.splitlines()
    if len(lines) < 3 or lines[0].strip() != "---":
        raise SkillPackageError(f"{source_path} does not start with YAML frontmatter")

    end_idx = None
    for idx, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_idx = idx
            break
    if end_idx is None:
        raise SkillPackageError(f"{source_path} has unterminated YAML frontmatter")

    parsed = yaml.safe_load("\n".join(lines[1:end_idx])) or {}
    if not isinstance(parsed, dict):
        raise SkillPackageError(f"{source_path} frontmatter must be a mapping")

    body = "\n".join(lines[end_idx + 1 :]).strip()
    return parsed, body


def load_definition(definition_path: Path) -> tuple[dict[str, Any], str]:
    """Load one Bio-Harness tool contract definition.

    Args:
        definition_path: Markdown definition path under the definitions
            directory.

    Returns:
        Parsed metadata and Markdown body.

    Raises:
        SkillPackageError: If required contract fields are missing.
    """
    metadata, body = _split_frontmatter(
        definition_path.read_text(encoding="utf-8"),
        definition_path,
    )
    missing = [field for field in REQUIRED_CONTRACT_FIELDS if field not in metadata]
    if missing:
        raise SkillPackageError(f"{definition_path} is missing required fields: {missing}")
    if not str(metadata.get("name", "")).strip():
        raise SkillPackageError(f"{definition_path} has an empty skill name")
    if not isinstance(metadata.get("parameters"), dict):
        raise SkillPackageError(f"{definition_path} parameters must be a mapping")
    return metadata, body


def _listify(value: Any) -> list[str]:
    """Normalize metadata values to a list of display strings."""
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    text = str(value).strip()
    return [text] if text else []


def _sentence(value: Any, fallback: str) -> str:
    """Return a display sentence from metadata with a fallback."""
    text = str(value or "").strip()
    return text.rstrip(".") + "." if text else fallback


def _bullet_lines(values: list[str], *, fallback: str) -> list[str]:
    """Render Markdown bullet lines."""
    if not values:
        return [f"- {fallback}"]
    return [f"- {value}" for value in values]


def _parameter_lines(parameters: dict[str, Any]) -> list[str]:
    """Render parameter metadata as concise Markdown bullets."""
    lines: list[str] = []
    for name, spec in sorted(parameters.items()):
        if isinstance(spec, dict):
            description = str(spec.get("description") or "No description provided.").strip()
            required = "required" if spec.get("required") else "optional"
            value_type = str(spec.get("type") or "value").strip()
            lines.append(f"- `{name}` ({value_type}, {required}): {description}")
        else:
            lines.append(f"- `{name}`: {spec}")
    return lines or ["- No structured inputs declared."]


def _format_system_requirements(metadata: dict[str, Any]) -> list[str]:
    """Render system requirements and external tools."""
    lines = _bullet_lines(
        _listify(metadata.get("tools_required")),
        fallback="No external tools declared.",
    )
    requirements = metadata.get("system_requirements")
    if isinstance(requirements, dict) and requirements:
        for key, value in sorted(requirements.items()):
            lines.append(f"- `{key}`: {value}")
    return lines


def _source_notes(body: str) -> list[str]:
    """Render original definition body notes when useful."""
    if not body:
        return []
    return [
        "## Source Notes",
        "",
        "The source contract includes these notes:",
        "",
        body,
        "",
    ]


def render_skill_markdown(
    metadata: dict[str, Any],
    body: str,
    *,
    source_definition: Path,
) -> str:
    """Render a standard ``SKILL.md`` file from a tool contract.

    Args:
        metadata: Parsed source contract metadata.
        body: Original Markdown body after frontmatter.
        source_definition: Repo-relative source definition path.

    Returns:
        Complete Markdown text for ``SKILL.md``.
    """
    name = str(metadata["name"]).strip()
    description = str(metadata["description"]).strip()
    when_to_use = _sentence(
        metadata.get("when_to_use"),
        f"Use this capability when the workflow requires `{name}`.",
    )
    when_not_to_use = _sentence(
        metadata.get("when_not_to_use"),
        "Do not use this capability when its required inputs or assumptions are not met.",
    )
    output_types = _listify(metadata.get("output_types"))
    input_types = _listify(metadata.get("input_types"))
    capabilities = _listify(metadata.get("capabilities"))
    analysis_categories = _listify(metadata.get("analysis_categories"))
    command_template = str(metadata.get("command_template") or "").strip()

    frontmatter = yaml.safe_dump(
        {"name": name, "description": description},
        sort_keys=False,
        allow_unicode=False,
    ).strip()
    sections = [
        "---",
        frontmatter,
        "---",
        "",
        GENERATED_HEADER,
        f"<!-- Source contract: {source_definition.as_posix()} -->",
        "",
        f"# {name}",
        "",
        "## What This Does",
        description,
        "",
        "## Use This Skill When",
        f"- {when_to_use}",
        *[f"- Capability: {item}" for item in capabilities],
        *[f"- Analysis category: {item}" for item in analysis_categories],
        "",
        "## Do Not Use This Skill When",
        f"- {when_not_to_use}",
        "",
        "## Required Inputs",
        *_parameter_lines(metadata.get("parameters") or {}),
        "",
        "## Input Types",
        *_bullet_lines(input_types, fallback="No input type metadata declared."),
        "",
        "## Expected Outputs",
        *_bullet_lines(output_types, fallback="No output type metadata declared."),
        "",
        "## Tools And Requirements",
        *_format_system_requirements(metadata),
        "",
        "## Execution Contract",
        (
            "The harness executes the typed contract in `contract.yaml`. "
            "Do not invent file paths, skip required inputs, or bypass the wrapper."
        ),
        "",
    ]
    if command_template:
        sections.extend(
            [
                "Wrapper command template:",
                "",
                "```text",
                command_template,
                "```",
                "",
            ]
        )
    sections.extend(
        [
            "## Validation Notes",
            (
                "The harness should verify required outputs exist and match the "
                "declared artifact roles before downstream steps use them."
            ),
            "",
            *_source_notes(body),
        ]
    )
    return "\n".join(sections).rstrip() + "\n"


def _contract_payload(metadata: dict[str, Any], *, source_definition: Path) -> dict[str, Any]:
    """Return a YAML-serializable contract payload for the generated package."""
    payload = dict(metadata)
    payload["source_definition"] = source_definition.as_posix()
    payload["generated_by"] = "scripts/generate_standard_skill_packages.py"
    return payload


def generate_package(definition_path: Path, catalog_dir: Path, repo_root: Path) -> Path:
    """Generate one standard skill package from one definition file.

    Args:
        definition_path: Source definition file.
        catalog_dir: Directory receiving generated package directories.
        repo_root: Repository root used for stable relative paths.

    Returns:
        Path to the generated package directory.
    """
    metadata, body = load_definition(definition_path)
    name = str(metadata["name"]).strip()
    package_dir = catalog_dir / name
    package_dir.mkdir(parents=True, exist_ok=True)

    try:
        source_definition = definition_path.resolve().relative_to(repo_root.resolve())
    except ValueError:
        source_definition = definition_path

    skill_md = render_skill_markdown(metadata, body, source_definition=source_definition)
    contract_yaml = yaml.safe_dump(
        _contract_payload(metadata, source_definition=source_definition),
        sort_keys=False,
        allow_unicode=False,
        width=100,
    )

    (package_dir / "SKILL.md").write_text(skill_md, encoding="utf-8")
    (package_dir / "contract.yaml").write_text(contract_yaml, encoding="utf-8")
    return package_dir


def generate_packages(definitions_dir: Path, catalog_dir: Path, repo_root: Path) -> list[Path]:
    """Generate standard skill packages for every source definition.

    Args:
        definitions_dir: Directory containing source ``*.md`` contracts.
        catalog_dir: Output catalog directory.
        repo_root: Repository root for stable generated references.

    Returns:
        Sorted list of generated package directories.
    """
    generated: list[Path] = []
    for definition_path in sorted(definitions_dir.glob("*.md")):
        if definition_path.name == "template.md":
            continue
        generated.append(generate_package(definition_path, catalog_dir, repo_root))
    return generated


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--definitions-dir",
        type=Path,
        default=DEFAULT_DEFINITIONS_DIR,
        help="Directory containing Bio-Harness Markdown tool contracts.",
    )
    parser.add_argument(
        "--catalog-dir",
        type=Path,
        default=DEFAULT_CATALOG_DIR,
        help="Directory where standard SKILL.md packages will be generated.",
    )
    return parser.parse_args()


def main() -> int:
    """Generate all standard skill packages."""
    args = parse_args()
    generated = generate_packages(
        args.definitions_dir.resolve(),
        args.catalog_dir.resolve(),
        PROJECT_ROOT,
    )
    print(f"Generated {len(generated)} standard skill packages in {args.catalog_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
